# -*- coding: utf-8 -*-
"""model evaluation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FasOEAFfLPwKpnYyZaf1Yti6EBvW9MlO

## Global Development Clustering Project

Key Features in Dataset

Below are important variables included:

 Economic Indicators:

GDP – Gross Domestic Product

Business Tax – Tax rate for businesses

Lending Rate – Interest rate

Energy Usage – Energy consumption



 Population & Health Indicators:

Birth Rate – Number of births per 1000 people

Infant Mortality – Infant deaths per 1000 births

Life Expectancy (Female) – Average lifespan

Health Expenditure % GDP – Health spending as % of GDP

Health Expenditure per Capita



 Development & Technology Indicators:

Internet Usage – % of population using internet

Ease of Business – Business friendliness index

Days to Start Business

Hours to Do Tax



 Environmental Indicator:

CO2 Emissions – Carbon emissions level

The dataset contains economic, social, and development indicators of various countries across the world.
"""

# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

#read the dataset
df=pd.read_excel("/content/World_development_mesurement (1) (1).xlsx")

df.head()

df.info()

df.describe()

df.shape

df.dtypes

#Separate Numerical Columns
num_cols=df.select_dtypes(include=np.number).columns
num_cols

# categorical cxolumns
cat_cols=df.select_dtypes(include='object').columns
cat_cols

# string to numeric conversion
def clean_currency(s):
    if pd.isnull(s): return np.nan
    return float(str(s).replace('$','').replace(',','').strip())

def clean_pct(s):
    if pd.isnull(s): return np.nan
    return float(str(s).replace('%','').strip())

df['GDP'] = df['GDP'].apply(clean_currency)
df['Health Exp/Capita'] = df['Health Exp/Capita'].apply(clean_currency)
df['Tourism Inbound']   = df['Tourism Inbound'].apply(clean_currency)
df['Tourism Outbound']  = df['Tourism Outbound'].apply(clean_currency)
df['Business Tax Rate'] = df['Business Tax Rate'].apply(clean_pct)
print("Currency and percentage columns converted to float.")
print(df[['GDP','Health Exp/Capita','Tourism Inbound','Business Tax Rate']].dtypes)

#nul values
df.isnull().sum().sort_values(ascending=False)

#high missing values dropping
threshold = 90  # drop if >90% missing
missing = df.isnull().sum().sort_values(ascending=False)
missing_pct = (missing / len(df) * 100).round(2)
cols_to_drop = missing_pct[missing_pct > threshold].index.tolist()
print(f"Dropping columns with >{threshold}% missing: {cols_to_drop}")
df.drop(columns=cols_to_drop, inplace=True)
print(f"Shape after drop: {df.shape}")

#filling missing values
num_cols = df.select_dtypes(include=np.number).columns
for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)

df.isnull().sum()

df.head(3)

#checking duplicates
df.duplicated().sum()

#no duplicates found

# drop irrelevant cols
df.set_index('Country',inplace=True)
df.drop(columns=['Number of Records'], inplace=True, errors='ignore')
print(df.columns.tolist())

# categorical variables encoding
from sklearn.preprocessing import StandardScaler,MinMaxScaler,LabelEncoder

other_cat_cols=df.select_dtypes(include='object').columns.tolist()
print("pending categorical columns ",other_cat_cols)

#all features are categorical

#normalization
#min max scaling

min_max=MinMaxScaler()
df_min_max=pd.DataFrame(min_max.fit_transform(df),columns=df.columns,index=df.index)
df_min_max

#Standard Scaling
std_sca=StandardScaler()
df_sca=pd.DataFrame(std_sca.fit_transform(df),columns=df.columns,index=df.index)
df_sca

# log transformation

df_log = df.copy()
log_features = ['GDP','Tourism Inbound','Tourism Outbound',
                'Health Exp/Capita','Mobile Phone Usage',
                'CO2 Emissions','Energy Usage','Population Total']
for col in log_features:
    if col in df_log.columns:
        df_log[col] = np.log1p(df_log[col])
print("Log transformation completed.")
df_log.head()

# feature enginnering

clustering_features = [
    'Birth Rate', 'CO2 Emissions', 'Days to Start Business',
    'Energy Usage', 'GDP', 'Health Exp % GDP', 'Health Exp/Capita',
    'Hours to do Tax', 'Infant Mortality Rate', 'Internet Usage',
    'Lending Interest', 'Life Expectancy Female', 'Life Expectancy Male',
    'Mobile Phone Usage', 'Population 0-14', 'Population 15-64',
    'Population 65+', 'Population Total', 'Population Urban',
    'Tourism Inbound', 'Tourism Outbound', 'Business Tax Rate'
]
clustering_features = [c for c in clustering_features if c in df.columns]
df_feat = df[clustering_features].copy()
print(f" Selected {len(clustering_features)} features for clustering.")
print(clustering_features)

df['GDP_per_Person'] = df['GDP'] / df['Population Total']
df['Health_Efficiency'] = df['Life Expectancy Female'] / df['Health Exp % GDP']



# correleation
corr_matrix = df_feat.corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')

corr = df_feat.corr()
print("Top positive correlations:")
corr_pairs = corr.abs().unstack().sort_values(ascending=False)
corr_pairs = corr_pairs[corr_pairs < 1.0].drop_duplicates()
print(corr_pairs.head(10).round(3).to_string())

# Final feature dataframe shape
print(f"\n Final Feature Dataset Shape: {df_feat.shape}")
# Final selected features
print(f"\n Total Final Features: {len(df_feat.columns)}")
print("\n Final Feature List:")
for i, col in enumerate(df_feat.columns, 1):
    print(f"{i}. {col}")

#outlier detection

#boxplot
for col in df_feat.columns:
    plt.figure(figsize=(6,4))
    sns.boxplot(y=df_feat[col])
    plt.title(f"Boxplot of {col}")
    plt.ylabel(col)
    plt.tight_layout()
    plt.show()

# Outlier Capping Function (IQR Method)
def outlier_capping(df_feat, column):
    Q1 = df_feat[column].quantile(0.25)
    Q3 = df_feat[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_extreme = Q1 - 1.5 * IQR
    upper_extreme = Q3 + 1.5 * IQR

    df_feat[column] = df_feat[column].apply(
        lambda x: lower_extreme if x < lower_extreme
        else upper_extreme if x > upper_extreme
        else x
    )
# Apply to all numeric columns
for col in df_feat.select_dtypes(include=['int64','float64']).columns:
    outlier_capping(df_feat, col)

print("Outlier capping completed successfully.")

#histogram
for col in df_feat.columns:
    plt.figure(figsize=(6,4))
    sns.histplot(df_feat[col], kde=True)
    plt.title(f"Distribution of {col}")
    plt.xlabel(col)
    plt.ylabel("Frequency")
    plt.tight_layout()
    plt.show()

#density plot

for col in df_feat.columns:
    plt.figure(figsize=(6,4))
    sns.kdeplot(df_feat[col], fill=True)
    plt.title(f"Density Plot (KDE) of {col}")
    plt.xlabel(col)
    plt.ylabel("Density")
    plt.tight_layout()
    plt.show()

#pairplot
sns.pairplot(df_feat, diag_kind='kde')
plt.show()

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df_feat)
print("Scaling completed.")

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
sil_scores = []
K = range(2, 11)
for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(df_scaled)   # USE SCALED DATA
    score = silhouette_score(df_scaled, labels)
    sil_scores.append(score)
plt.figure(figsize=(6,4))
plt.plot(K, sil_scores, marker='o')
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Silhouette Score")
plt.grid(True)
plt.show()

#Optimal number of clusters = 4

#pca

# apply pca to all components
from sklearn.decomposition import PCA
pca = PCA()
pca.fit(df_scaled)
explained_variance = pca.explained_variance_ratio_
print("Explained Variance Ratio:")
print(explained_variance)

#cumulative explained variance
cumulative_variance = np.cumsum(explained_variance)
plt.figure(figsize=(6,4))
plt.plot(range(1, len(cumulative_variance)+1),
         cumulative_variance, marker='o')
plt.axhline(y=0.90, color='r', linestyle='--')
plt.title("Cumulative Explained Variance")
plt.xlabel("Principal Components")
plt.ylabel("Cumulative Variance")
plt.grid(True)
plt.show()
print("Cumulative Variance:")
print(cumulative_variance)

#optimal components
n_components = np.argmax(cumulative_variance >= 0.90) + 1
print("Optimal Components:", n_components)
pca_final = PCA(n_components=n_components)
df_pca = pca_final.fit_transform(df_scaled)
print("Reduced Dataset Shape:", df_pca.shape)

# pca 2d visualization
pca_2d = PCA(n_components=2)
pca_2d_data = pca_2d.fit_transform(df_scaled)
plt.figure(figsize=(7,5))
plt.scatter(pca_2d_data[:,0], pca_2d_data[:,1])
plt.title("2D PCA Projection")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.grid(True)
plt.show()

"""# model evaluation

models used :

1.k means clustering

2.DBSCAN

3.Hierarchial clustering

4.Mean shifting clustering

5.Gaussian Mixture Model


Additionally we did an supervised ml model also :

6.KNN Model

model -1 : k means clustering
"""

# KMeans
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
clusters = kmeans.fit_predict(df_pca)
df_feat['Cluster'] = clusters
print(df_feat['Cluster'].value_counts())

plt.figure(figsize=(7,5))
plt.scatter(
    df_pca[:,0],
    df_pca[:,1],
    c=df_feat['Cluster'],
    cmap='viridis'
)
plt.title("Cluster Visualization using PCA")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.colorbar(label="Cluster")
plt.grid(True)
plt.show()

cluster_summary = df_feat.groupby('Cluster').mean(numeric_only=True)
cluster_summary

from sklearn.metrics import silhouette_score
k_means_score = silhouette_score(df_pca, clusters)
k_means_score

df_feat['Cluster'].value_counts()

"""model 2 : Dbscan model"""

from sklearn.cluster import DBSCAN

dbscan=DBSCAN(eps=0.8,min_samples=3)
db_clusters=dbscan.fit_predict(df_pca)
df_feat['dbscan_cluster']=db_clusters
dbscan.labels_

plt.figure(figsize=(7,5))
plt.scatter(
    df_pca[:,0],
    df_pca[:,1],
    c=db_clusters,
)
plt.title("DBSCAN")
plt.xlabel("Pca 1")
plt.ylabel("Pca 2")
plt.colorbar(label="Cluster")
plt.grid(True)
plt.show()

# with out removing noise
if len(set(db_clusters)) > 1:
    dbscan_score_noise= silhouette_score(df_pca, db_clusters)
    print("DBSCAN Silhouette Score:", dbscan_score_noise)
else:
    print("Silhouette score cannot be calculated (only one cluster).")

dbscan_summary = df_feat.groupby('dbscan_cluster').mean(numeric_only=True)
dbscan_summary

""" model 3 - hierarchial clustering"""

from scipy.cluster.hierarchy import dendrogram, linkage
linked = linkage(df_pca, method='ward')
plt.figure(figsize=(12,6))
dendrogram(linked)
plt.title("Hierarchical Clustering Dendrogram")
plt.xlabel("Data Points")
plt.ylabel("Distance")
plt.show()

from sklearn.cluster import AgglomerativeClustering
hierarchical = AgglomerativeClustering(n_clusters=3)
hier_clusters = hierarchical.fit_predict(df_pca)
df_feat['Hierarchical_Cluster'] = hier_clusters
print(df_feat['Hierarchical_Cluster'].value_counts())

plt.figure(figsize=(7,5))
plt.scatter(
    df_pca[:,0],
    df_pca[:,1],
    c=hier_clusters,
    cmap='rainbow'
)
plt.title("Hierarchical Clustering")
plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
plt.colorbar(label="Cluster")
plt.grid(True)
plt.show()

hierarchial_score=silhouette_score(df_pca, hier_clusters)
print("Hierarchical Silhouette Score:", hierarchial_score)

hier_summary = df_feat.groupby('Hierarchical_Cluster').mean(numeric_only=True)
print(hier_summary)

""" model 4 : mean shift"""

from sklearn.cluster import MeanShift, estimate_bandwidth
bandwidth = estimate_bandwidth(df_pca, quantile=0.2)
print("Estimated bandwidth:", bandwidth)
mean_shift = MeanShift(bandwidth=3.5)
ms_clusters = mean_shift.fit_predict(df_pca)
df_feat['Mean_Shift_Cluster'] = ms_clusters
print(df_feat['Mean_Shift_Cluster'].value_counts())

plt.figure(figsize=(7,5))
plt.scatter(
    df_pca[:,0],
    df_pca[:,1],
    c=ms_clusters,
    cmap='viridis'
)
plt.title("Mean Shift Clustering")
plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
plt.colorbar(label="Cluster")

plt.show()

mean_shift_score = silhouette_score(df_pca, ms_clusters)
print("Mean Shift Silhouette Score:", mean_shift_score)

ms_summary = df_feat.groupby('Mean_Shift_Cluster').mean(numeric_only=True)
print(ms_summary)

"""model - 5 :Gaussian Mixture Model"""

from sklearn.mixture import GaussianMixture

#Creating GMM Model
gmm = GaussianMixture(n_components=3,covariance_type='full',  n_init=10,random_state=42)

# train and cluster predicting
best_score = -1  # high score
best_k = None # number of clusters
best_model = None # best model
for k in range(2,8):
    gmm = GaussianMixture(
        n_components=k,
        covariance_type='full',
        random_state=42
    )
    labels = gmm.fit_predict(df_pca)
    score = silhouette_score(df_pca, labels)
    print("Clusters:", k, "Score:", score)
    if score > best_score:
        best_score = score
        best_k = k
        best_model = labels
print("\nBest Clusters:", best_k)

df_feat['GMM_Cluster'] = best_model
df_feat['GMM_Cluster'].value_counts()

plt.figure(figsize=(7,5))
plt.scatter(
    df_pca[:,0],
    df_pca[:,1],
    c=df_feat['GMM_Cluster'],
    cmap='viridis'
)
plt.title("Gaussian Mixture Model")
plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
plt.colorbar(label="Cluster")
plt.grid(True)
plt.show()

gmm_score = silhouette_score(df_pca, df_feat['GMM_Cluster'])
print(" GMM Silhouette Score:", gmm_score)

gmm_summary = df_feat.groupby('GMM_Cluster').mean(numeric_only=True)
print(gmm_summary)

""" model 5 :
super vised model

k nearest neighbour knn model
"""

x=df_scaled
y=df_feat['Cluster']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)

y_pred_knn = knn.predict(x_test)

from sklearn.metrics import accuracy_score
knn_accuracy=accuracy_score(y_test, y_pred_knn)
print("KNN Accuracy:", knn_accuracy)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_knn))

print("====Model Evaluation Summary====")
print("KMeans Silhouette:", k_means_score)
print("DBSCAN Silhouette :", dbscan_score_noise)
print("Hierarchical Silhouette:", hierarchial_score)
print("Mean Shift Silhouette:", mean_shift_score)
print(" GMM Silhouette Score:", gmm_score)
print('======additional model======')
print("KNN Accuracy:", knn_accuracy)

"""Model Ranking :
1. KMeans : 0.284
2. Mean Shift : 0.277
3. GMM : 0.256
4. Hierarchical : 0.239
5. DBSCAN : 0.176
"""



import pickle

# Save df_pca
with open('df_pca.pkl', 'wb') as file:
    pickle.dump(df_pca, file)
print('df_pca saved to df_pca.pkl')

import pickle

# Save KMeans model
with open('kmeans_model.pkl', 'wb') as file:
    pickle.dump(kmeans, file)
print('KMeans model saved to kmeans_model.pkl')

import pickle

# Save DBSCAN model
with open('dbscan_model.pkl', 'wb') as file:
    pickle.dump(dbscan, file)
print('DBSCAN model saved to dbscan_model.pkl')

import pickle

# Save Hierarchical Clustering model
with open('hierarchical_model.pkl', 'wb') as file:
    pickle.dump(hierarchical, file)
print('Hierarchical Clustering model saved to hierarchical_model.pkl')

import pickle

# Save Mean Shift model
with open('mean_shift_model.pkl', 'wb') as file:
    pickle.dump(mean_shift, file)
print('Mean Shift model saved to mean_shift_model.pkl')

import pickle

# Save Gaussian Mixture Model (GMM)
# Note: best_model refers to the labels, not the GMM object itself.
# The GMM object 'gmm' was updated in the loop, so I'll save the last one fitted.
with open('gmm_model.pkl', 'wb') as file:
    pickle.dump(gmm, file)
print('Gaussian Mixture Model saved to gmm_model.pkl')

import pickle

# Save KNN model
with open('knn_model.pkl', 'wb') as file:
    pickle.dump(knn, file)
print('KNN model saved to knn_model.pkl')

df_feat.to_pickle('df_feat.pkl')